<?php
include('show.php');

if(!$conn){
    die("sorry we failed to connect: ". mysqli_connect_error());
}

if($_SERVER['REQUEST_METHOD']=='POST'){
    $name = $_POST['name'];
    $exno = $_POST['ExaminationNo'];
    $email = $_POST['email'];
    $contact = $_POST['contact'];
    $cer1 = $_POST['TC'];
    $cer2= $_POST['PC'];
    $ch1 = implode($cer1);
    $ch2 = implode($cer2);
}
$tc="";
$pc="";

if($cer1){
    $tc= "applied";
}else{
    $tc= "not applied";
}

if($cer2){
    $pc= "applied";
}else{
    $pc = "not applied";
}

$sqlcheck = "SELECT * FROM `college3` WHERE ExaminationNo = '$exno' ";  //fetching record from table of rollno entered by user if exists.
$resultcheck = mysqli_query($conn, $sqlcheck);
$rowcheck= mysqli_num_rows($resultcheck);
$row = mysqli_fetch_assoc($resultcheck);
if($rowcheck>=1){

    if($tc == 'applied' && $pc == 'applied'){
    $sql = "UPDATE `college3` SET `TC`='$tc' , `provCert`='$pc' WHERE ExaminationNo = '$exno'";
    $result = mysqli_query($conn, $sql);
    }elseif($tc == 'applied'){
        $sql = "UPDATE `college3` SET `TC`='$tc' WHERE ExaminationNo = '$exno'";
        $result = mysqli_query($conn, $sql);
    }elseif($pc == 'applied'){
        $sql = "UPDATE `college3` SET `provCert`='$pc' WHERE ExaminationNo = '$exno'";
        $result = mysqli_query($conn, $sql);
    }else{
        echo "plz select any certificate";
        $result = false;
    }
    if($result){
        echo"Done1";
        writeMsg("mansisaxena670@gmail.com" , $name , $contact ,$exno,$cer1 ,$cer2);
        // writeMsg($email , $name , $contact ,$exno,$cer1 ,$cer2);
    }
}else{
    $sqlcheck2 = "SELECT * FROM `collegeOfficial` WHERE ExamRollno='$exno'";
    $resultcheck2 = mysqli_query($conn, $sqlcheck2);
    $rowcheck2= mysqli_num_rows($resultcheck2);
    $row2 = mysqli_fetch_assoc($resultcheck2);
    // echo $row2['Examination No'];
    if($rowcheck2 >=1){
         $sql = "INSERT INTO `college3`(`Name`, `ExaminationNo`, `email`, `contact` ,`TC`,`provCert`) VALUES ('$name','$exno','$email','$contact' , '$tc' ,'$pc')";  
         $result = mysqli_query($conn, $sql);
        if($result){
            echo"Done2";
            // writeMsg($email , $name , $contact ,$exno ,$cer1 ,$cer2);
            writeMsg("mansisaxena670@gmail.com" , $name , $contact ,$exno ,$cer1 ,$cer2);
        }  
    }else{
        header("location:usernot.html");
    }

}

function writeMsg($email , $name , $contact ,$exno ,$cer1 ,$cer2) {
        $to = "vishusaxena3110@gmail.com";
        $to2 = "$email";
        $certificate =  ($cer1 && $cer2) ? $cer1 . ' , '.$cer2 : $cer1.' '.$cer2 ;
        $subject = "Acknowledgement for " . $certificate ;
        // $subject2 = "mail from college";
        $message = "You will be informed via email for further updates.";
        $message2 = "This is an autogenerated email please do not reply to it.";
        
        // $checkbox = $ch1 . ' ' . $ch2 . ' ' . $ch3;

        $txt =" Student Name : ". ucwords($name) ."\r\n Email : " . $email . "\r\n Contact : " . $contact. "\r\n Examination Number : " . $exno. "\r\n Applied for certificate : " . $certificate;

        $txt2 ="Student Name : ". ucwords($name) ."\r\n Email : " . $email . "\r\n Contact : " . $contact. "\r\n Examination Number : " . $exno . "\r\n Applied for certificate : " . $certificate . "\r\n"."\r\n". $message . "\r\n"."\r\n" . $message2 ;
        $headers2 = "From: Bhaskaracharya College Of Applied Sciences";
        $headers = "$email";
        
        if($email!=NULL){
            mail($to,$subject,$txt,$headers);
            mail($to2,$subject,$txt2,$headers2);
            echo "send";
            header("location:thanks.html");
        }else{
            // echo "not send";
            header("location:regret.html");
        }
  }
  

// //  checking whether the user exists or not 
// $sqlcheck = "SELECT * FROM `collegetable2` WHERE RollNo= '$crn' ";  //fetching record from table of rollno entered by user if exists.
// $resultcheck = mysqli_query($conn, $sqlcheck);
// $rowcheck= mysqli_num_rows($resultcheck);
// $row = mysqli_fetch_assoc($resultcheck);



// if($rowcheck>=1){// if user has already applied applied for some certificate and trying to applying for more than you just have to update 

//     if ($ch1=='applied' && $ch2 == 'applied' && $ch3 == 'applied') {
//         $sql = "UPDATE `collegetable2` SET `TransferCertificate`='$ch1',`marksheet`='$ch2',`AchievmentCertificate`='$ch3' WHERE RollNo = '$crn' ";
        
//     }elseif($ch1 == "applied" && $ch2=="applied"){
//         $sql = "UPDATE `collegetable2` SET `TransferCertificate`='$ch1',`marksheet`='$ch2' WHERE RollNo = '$crn' ";

//     }elseif ($ch1 == "applied" && $ch3=="applied") {
//         $sql = "UPDATE `collegetable2` SET  `TransferCertificate`='$ch1',,`AchievmentCertificate`='$ch3' WHERE RollNo = '$crn' ";

//     }elseif ($ch2 == "applied" && $ch3=="applied") {
//         $sql = "UPDATE `collegetable2` SET `marksheet`='$ch2',`AchievmentCertificate`='$ch3' WHERE RollNo = '$crn' ";

//     }elseif ($ch1=='applied') {
//         $sql = "UPDATE `collegetable2` SET  `TransferCertificate`='$ch1' WHERE RollNo = '$crn' ";

//     }elseif ($ch2=='applied') {
//         $sql = "UPDATE `collegetable2` SET `marksheet`='$ch2' WHERE RollNo = '$crn' ";

//     }elseif ($ch3=='applied') {
//         $sql = "UPDATE `collegetable2` SET `AchievmentCertificate`='$ch3' WHERE RollNo = '$crn' ";
//     }
    
// }else if($rowcheck==0){

//     // cross checking the records enter by user
//     // firstly just check whether the student exists or not by matching the college rollno with studentOffice table

//     $sqlcheck2 = "SELECT * FROM `studentoffice` WHERE RollNO = '$crn'";
//     $resultcheck2 = mysqli_query($conn, $sqlcheck2);
//     $rowcheck2= mysqli_num_rows($resultcheck2);
//     if ($rowcheck2==1) {//if this is true it means student with this roll no exists 

//         $row2 = mysqli_fetch_assoc($resultcheck2);

//         $elements = array("name", "fathername","email","pincode","Enrollment number","college roll number","department","course");
        
//         $user = array(strtoupper($name), strtoupper($fathername),$email,$pincode,$en,$crn,strtoupper($dep),strtoupper($course));

//         $userOffice = array(strtoupper($row2['Name']),strtoupper($row2['father name']) ,$row2['email'],$row2['Pin code'], $row2['Enrolment No'] ,$row2['RollNo'] , strtoupper($row2['department']) , strtoupper($row2['course']));

//         for($i=0 ; $i<count($user); $i++){
//             if($user[$i] != $userOffice[$i]){
//                 // echo $elements[$i] . "is not correct entry";
//                 // echo $user[$i] , $userOffice[$i];
//                 $sql ="";
//                 break;
//             }else{
//                 $sql = "INSERT INTO `collegetable2`(`FirstName`, `MiddleName`, `LastName`, `FatherName`, `email`, `ContactNumber`, `pincode`, `EnrollmentNo`, `RollNo`, `department`, `course`, `TransferCertificate`, `marksheet`, `AchievmentCertificate`) VALUES ('$fname','$mname','$lname','$fathername','$email','$contact','$pincode','$en','$crn','$dep','$course','$ch1','$ch2','$ch3')";
//             }
//         }
//     }
    
// }else{
//     // // echo "Student doesnot exists with this rollno";
//     // $sql = "";
//     $sql = "INSERT INTO `collegetable2`(`FirstName`, `MiddleName`, `LastName`, `FatherName`, `email`, `ContactNumber`, `pincode`, `EnrollmentNo`, `RollNo`, `department`, `course`, `TransferCertificate`, `marksheet`, `AchievmentCertificate`) VALUES ('$fname','$mname','$lname','$fathername','$email','$contact','$pincode','$en','$crn','$dep','$course','$ch1','$ch2','$ch3')";
// }


// if($sql!=""){

//     $result = mysqli_query($conn, $sql);
//     if($result){
        
//         $to = "vishusaxena3110@gmail.com";
//         $to2 = "$email";
//         $subject = "mail for certificate widthrawing";
//         $subject2 = "mail from college";
//         $name = $fname ." ".$mname." ".$lname;
//         $message = "You will be informed via email for further updates.";
//         $message2 = "This is an autogenerated email please donot reply to it.";
//         $checkbox = $ch1 . ' ' . $ch2 . ' ' . $ch3;

//         $txt =" Name : ". ucfirst($name) . "\r\n Father's Name : " .ucfirst($fathername) . "\r\n Email : " . $email . "\r\n Contact : " . $contact . "\r\n College Roll Number : " . $crn . "\r\n Enrollment Number : " . $en . "\r\n Department : " . $dep . "\r\n Course. : " . $course . "\r\n Applied for Certificates. : " . $checkbox  ;

//         $txt2 = "Student Name : ". ucfirst($name) ."\r\n Father's Name : " . ucfirst($fathername) ."\r\n Contact : " . $contact ."\r\n Email : " . $email ."\r\n Enrollment Number : " . $en ."\r\n College Roll Number : " . $crn ."\r\n Course : " . $course ."\r\n Department : " . $dep ."\r\n Applied for certificate : " . $checkbox  . "\r\n " ."\r\n " .  $message  . "\r\n " .
//         "\r\n " . $message2;
//         $headers2 = "From: Bhaskaracharya College Of Applied Sciences";
//         $headers = "$email";

//         if($email!=NULL){
//             mail($to,$subject,$txt,$headers);
//             mail($to2,$subject2,$txt2,$headers2);
//             // echo "send";
//             header("location:thanks.html");
//         }else{
//             // echo "not send";
//             header("location:regret.html");
//         }
//     }else{
//         header("Location:regret.html");
//         // echo"connection error";
//     }
// }else{
//     echo'<div class="alert alert-danger alert-dismissible fade show" role="alert">
//     <strong> wrong details.</strong>
//     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
//     <span aria-hidden="true"><a href="index.html">ok</a></span>
//     </button>
//   </div>';
// }
   
//     echo"there is an error";
//     echo mysqli_error($conn);
//     header("Location:regret.html");
?>