<?php

include('connect.php');

$to = "vishusaxena3110@gmail.com";
    $to2 = "$email";
    $subject = "mail for certificate widthrawing";
    $subject2 = "mail from college";
    $name = $fname ." ".$mname." ".$lname;
    $message = "you will be informed via email for further updates.";
    $message2 = "This is an autogenerated email please donot reply to it.";
    $checkbox = $ch1 . ' ' . $ch2 . ' ' . $ch3;

    $txt =" Name = ". $name . "\r\n father's Name = " . $fathername . "\r\n email = " . $email . "\r\n contact = " . $contact . "\r\n College Rollno. = " . $crn . "\r\n Enrollment no. = " . $en . "\r\n Department = " . $dep . "\r\n course. = " . $course . "\r\n Applied for Certificates. = " . $checkbox  ;

    $txt2 =" Name = ". $name ."\r\n FatherName = " . $fathername ."\r\n contact = " . $contact ."\r\n Email = " . $email ."\r\n Enrollment No = " . $en ."\r\n College Rollno. = " . $crn ."\r\n course = " . $course ."\r\n department = " . $dep ."\r\n applied for certificate = " . $checkbox  . "\r\n " .  $message  . "\r\n " . $message2;
    $headers2 = "From: bhaskar acharya college of applied science";
    $headers = "$email";

    if($email!=NULL){
        // mail($to,$subject,$txt,$headers);
        // mail($to2,$subject2,$txt2,$headers2);
        echo "send";
        // header("location:thanks.html");
    }else{
        echo "not send";
        // header("location:regret.html");
    }

?>
