<?php
    include('../show.php');
    $sn = $_GET['id'];
    if($sn){
        $status = "rejected";
        $sql = "SELECT * FROM `college3` WHERE  ExaminationNo = '$sn' ";
    
        $sql2 = "UPDATE `college3` SET `TC`= '$status' WHERE ExaminationNo = '$sn' ";
    
        $result = mysqli_query($conn, $sql);
        $result2 = mysqli_query($conn, $sql2);
        $row = mysqli_fetch_assoc($result);
        $rowcheck= mysqli_num_rows($result);
    
        if($result2)
        {
            $email= $row['email'];
            $to = "$email";
            $subject = "mail from college";
            $name = $row['Name'];
            $message = "your applicatin for Transfer Certificate is rejected.";
            $message2 = "This is an autogenerated email please donot reply to it.";
            $txt =" Name = ". $name ."\r\n Email = " . $row['email'] ."\r\n Examination Number = " . $row['ExaminationNo']  . "\r\n " .  $message  . "\r\n " . $message2;
            $headers = "From: bhaskar acharya college of applied science";
            if($email!=NULL){
                // mail($to,$subject,$txt,$headers);
                // echo 'sent';
                header("Location: ../table.php");
            }else{
                header("Location: ../crossed.html");
            }
        }
    }else{
        header("Location: ../crossed2.html");
    }
   
?>